# Generated by Django 4.2.4 on 2023-11-16 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DesempenhoEmpresarial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('espectativa', models.CharField(max_length=50)),
                ('totalVendaAnual', models.CharField(max_length=50)),
                ('mes', models.CharField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='DesempenhoMensalVendas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('espectativa', models.CharField(max_length=50)),
                ('totalVendaNoMes', models.CharField(max_length=50)),
                ('mes', models.CharField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DesempenhoTrimestralVendas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('espectativa', models.CharField(max_length=50)),
                ('totalVendaNoTrimestre', models.CharField(max_length=50)),
                ('trimestre', models.CharField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MetasTendenciasVendas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('espectativa', models.CharField(max_length=50)),
                ('totalVendaNoMes', models.CharField(max_length=50)),
                ('mes', models.CharField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='MetasVendas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('espectativa', models.CharField(max_length=50)),
                ('totalVendaNoMes', models.CharField(max_length=50)),
                ('mes', models.CharField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
